# Generated by Django 4.0.3 on 2022-06-10 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_supplier_mobileno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='mobileNo',
            field=models.IntegerField(null=True, validators=[django.core.validators.RegexValidator(message='Enter Valid Mobile No', regex='^[0-9]+\\d{10,13}$')]),
        ),
        migrations.AlterField(
            model_name='agency',
            name='mobileNo',
            field=models.IntegerField(null=True, validators=[django.core.validators.RegexValidator(message='Enter Valid Mobile No', regex='^[0-9]+\\d{10,13}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobileNo',
            field=models.IntegerField(null=True, validators=[django.core.validators.RegexValidator(message='Enter Valid Mobile No', regex='^[0-9]+\\d{10,13}$')]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='mobileNo',
            field=models.IntegerField(null=True, validators=[django.core.validators.RegexValidator(message='Enter Valid Mobile No', regex='^[0-9]+\\d{10,13}$')]),
        ),
        migrations.AlterField(
            model_name='worker',
            name='mobileNo',
            field=models.IntegerField(null=True, validators=[django.core.validators.RegexValidator(message='Enter Valid Mobile No', regex='^[0-9]+\\d{10,13}$')]),
        ),
    ]
