# Generated by Django 4.0.3 on 2022-06-02 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_actor_mobileno_alter_customer_mobileno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='mobileNo',
            field=models.CharField(max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Enter Valid Mobile No', regex='^(05)\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='profiles/'),
        ),
    ]
