# Generated by Django 4.0.3 on 2022-06-07 12:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0025_alter_actor_mobileno_alter_agency_mobileno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='mobileNo',
            field=models.IntegerField(null=True, validators=[django.core.validators.RegexValidator(message='Enter Valid Mobile No', regex='^(05)\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='actor',
            name='model',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='mobileNo',
            field=models.IntegerField(null=True, validators=[django.core.validators.RegexValidator(message='Enter Valid Mobile No', regex='^(05)\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='agency',
            name='social_website',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobileNo',
            field=models.IntegerField(null=True, validators=[django.core.validators.RegexValidator(message='Enter Valid Mobile No', regex='^(05)\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='social_website',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='mobileNo',
            field=models.IntegerField(null=True, validators=[django.core.validators.RegexValidator(message='Enter Valid Mobile No', regex='^(05)\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='social_website',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='mobileNo',
            field=models.IntegerField(null=True, validators=[django.core.validators.RegexValidator(message='Enter Valid Mobile No', regex='^(05)\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='worker',
            name='short_intro',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='worker',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
        ),
    ]
