# Generated by Django 4.0.3 on 2022-06-09 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_worker_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='timeDuration',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Enter Valid Mobile No', regex='^[0-9]*(?P<Days>)[0-9]*(?P<Months>)$')]),
        ),
    ]
