# Generated by Django 4.0.3 on 2022-06-10 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_premise_timeduration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premise',
            name='timeDuration',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Enter Valid Mobile No', regex='^[0-30]*Days [0-12]*Months$')]),
        ),
    ]
