# Generated by Django 4.0.3 on 2022-06-10 20:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_rename_orderstatus_garment_orderstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='mobileNo',
            field=models.IntegerField(null=True, validators=[django.core.validators.RegexValidator(message='Enter Valid Mobile No', regex='^[0-9]+\\d{10,13}$')]),
        ),
    ]
